// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_zJhbk3Jrh6ffwX4RDsoZyc3vgJU8mNk',
    appId: '1:129840975624:web:39e8220ef12aaa8ab326bd',
    messagingSenderId: '129840975624',
    projectId: 'flutter-project1216',
    authDomain: 'flutter-project1216.firebaseapp.com',
    storageBucket: 'flutter-project1216.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMOZNbv8cPvkmuH1kpi7HpgKXaLwJ-q1A',
    appId: '1:129840975624:android:924b2b17d841dd49b326bd',
    messagingSenderId: '129840975624',
    projectId: 'flutter-project1216',
    storageBucket: 'flutter-project1216.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_zJhbk3Jrh6ffwX4RDsoZyc3vgJU8mNk',
    appId: '1:129840975624:web:77b1d9c593f25513b326bd',
    messagingSenderId: '129840975624',
    projectId: 'flutter-project1216',
    authDomain: 'flutter-project1216.firebaseapp.com',
    storageBucket: 'flutter-project1216.appspot.com',
  );
}
